#----
server:
  port: 10001
spring:
  application:
    name: config-server
  #git repository
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          search-paths: /config-repo/dev/
          uri: https://github.com/riceincoke/spring_cloud_web_spider_pro_repo.git
          password:
          username:
          basedir: f:/my_git_cache
      label: master
      profile: on
  #rabbitmq
  rabbitmq:
    connection-timeout: 0
    template:
      retry:
        enabled: true
    password: admin
    port: 5672
    host: ${spring.cloud.client.ipAddress}
    virtual-host: /
    username: admin
management:
  security:
    enabled: false
eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    instance-id: ${spring.application.name}-${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 10
  client:
    eureka-service-url-poll-interval-seconds: 300
    register-with-eureka: true
    service-url:
      defaultZone: http://${spring.cloud.client.ipAddress}:3001/eureka/
    registry-fetch-interval-seconds: 10
info:
  number: 15282648585
  provider: ${eureka.instance.instance-id}
  groupId: ${project.groupId}
  artifactId: ${project.artifactId}
  version: ${project.version}
