#---
spring:
  application:
    name: zuul-server
server:
  port: 9999
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
management:
  security:
    enabled: false
eureka:
  instance:
    instance-id: ${spring.application.name}.${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 60
    lease-renewal-interval-in-seconds: 15
  client:
    eureka-service-url-poll-interval-seconds: 300
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${spring.cloud.client.ipAddress}:3001/eureka/
    registry-fetch-interval-seconds: 10
ribbon:
  ConnectTimeout: 10000
  eureka:
    enabled: true
  ReadTimeout: 10000
zuul:
  retryable: false
  routes:
    feign-consumer: /fm/**
  ignored-services: *
  add-host-header: true
  host:
    connect-timeout-millis: 5000
    socket-timeout-millis: 5000
info:
  number: 15282648585
  provider: ${eureka.instance.instance-id}
  groupId: ${project.groupId}
  artifactId: ${project.artifactId}
  version: ${project.version}
